### ISSUE TITLE
spPeoplePicker dialog not functioning in Chrome

### ISSUE THREAD

**Issue by rwfeather** [sympmarc/KOBindings#3]
Currently trying to build a SharePoint application, and I was hoping to be able to use the people picker included here.

Uploading the files to the Site Assets and opening **peoplePickerExample.aspx**, after clicking to open the dialog, it pops up. It functions fine until you close it at which point the callback provided is not called. No discernible error is shown in the developer console, and the page resumes what it was doing as if the binding was never activated, the field remains "Nobody". This is in Chrome 43 using SharePoint 2010.

It all works fine when opened up in IE however.

My guess is that this has something to do with [this Chrome deprecation](http://blog.chromium.org/2014/07/disabling-showmodaldialog.html), but I'm not sure. It's possible that I am doing something wrong with my deployment of the KOBindings library but I don't think so, given that it works in IE.

If the deprecation is the issue, could there be some workaround or similar functionality? I'd be willing to do the work and submit a pull request, I'm just not sure of the direction to go in. I'm sure it would be easier to just note in the docs that it no longer works in chrome.

**Comment by jkerski** [comment]
I was not able to reproduce the issue in Chrome.  I am using version 43.0.2357.134.  Can you confirm the version you are using?

**Comment by rwfeather** [comment]
Confirmed. Running:
- Chrome 43.0.2357.134 : Doesn't work
- IE 11.0.9600.17914 : Works fine

Uploaded a clean version of the KOBindings repository to my site assets. Disabled all extensions in Chrome.

Following it in the debugger, the problem occurs here:

``` javascript
//Call Dialog
dialogHandle = commonShowModalDialog(dialogURL, dialogOptions, function(searchResult) {
    var xmlDoc = $.parseXML(searchResult);
    var $xml = $(xmlDoc);
    //Get User ID
    var fqn = $xml.find('Entity').attr('Key');
    //Get Display Text
    ...
```

Execution hits the modal dialog and causes it to pop up. The dialog functions as expected, but on return, the callback is not executed and the deferred is not resolved.

I don't have the most experience in SharePoint, so i'm not sure if its something different on the server side (which I don't have access to configure).

I appreciate the quick response.

**Comment by jkerski** [comment]
Since you don't have access to the server.  Could you tell me the version of SharePoint 2010 you are on?  If you log into the site collection with SharePoint Designer you should see something like this:
![image](https://cloud.githubusercontent.com/assets/12315802/8816795/61fd315a-2ff9-11e5-98fc-5297d2548f7e.png)

**Comment by rwfeather** [comment]
Sharepoint Version: 4 (14.0.0.7145)

**Comment by jkerski** [comment]
Okay, let me see if I can recreate the issue or find an alternative to commonShowModalDialog.

**Comment by rwfeather** [comment]
I will keep looking into it as well. Thank you!

**Comment by jkerski** [comment]
I think we can skip the commonShowModalDialog if we use People.asmx with SPServices.  I'll get a rough view of a search screen uploaded on my fork (/jkerski) for you to take a look at.  Since you're using Bootstrap this could be put into a bootstrap modal. Thoughts?

**Comment by rwfeather** [comment]
That sounds like a good alternative.

**Comment by jkerski** [comment]
If you go to https://github.com/jkerski/KOBindings try peoplePickerExample2.aspx.  It's just the search for now, but we could get that into a Bootstrap modal and then into a custom binding.
